apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: photoprism
  namespace: photoprism
spec:
  releaseName: photoprism
  chart:
    spec:
      chart: photoprism
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
