apiVersion: v1
kind: Service
metadata:
  labels:
    io.codepool.service: mariadb
  name: mariadb
  namespace: databases
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    io.codepool.service: mariadb
