---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: flux-system
data:
  TIMEZONE: Asia/Kolkata
  NFS_SERVER: 192.168.0.225
  MARIADB_SERVICE: mariadb.databases.svc.cluster.local
  REDIS_SERVICE: redis-master.redis.svc.cluster.local
  PUBLIC_BLOG_DOMAIN: surajremanan.com
