apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
data:
    PUBLIC_DOMAIN: ENC[AES256_GCM,data:lUaMrrMs0ahAQVRSEyeDJw==,iv:UrO0Kcv7xaSDJx3axmdHszEiuEzbU8GAC151OZr0lDA=,tag:UoDSfrW89FHvuaNj9ieh8w==,type:str]
    CERT_SECRET_NAME: ENC[AES256_GCM,data:gD+A/t3rw6PtjTdsdTZkn8/dJCTDg3YN,iv:D1t/KSVTQWbZQ9CST/fmBvJDkGaePYOE0zHFSD3hgkA=,tag:J/Dcu88KT5SHHNArEJTBOA==,type:str]
    WIREGUARD_CONFIG: ENC[AES256_GCM,data:bhJOncYJYoYfhYRlE1Ndf09v3v/PhgfLvBmvi7QXy4bbkufyJYxdVyeCfhjSKoG6oVRbQgrV87heiZXqfu+tFwOjuDsCydj+6NOHhVFFrjAhOCOUDagDnUyUSCC2h7vCaHx2fDpdPw8CGGkutD8dAYLJgho32yEk1FRj6L+9IOI0KVwJP2230C/Hp8/2ycYEte4u8P/+P9szJ0ncBYJznNTAZS7cv41vSG1W5pjoNRTldU61uitWhTo4qzmGiI4HpOo7wS64yDrR0pcPjBUl7Qqko/z41nIJuLFzu7JDgcI6QsLj5UkHsNSUmcQvzVIKQYEmH8sNzXDRcbgHkAcxnPpQoXHySnT3H4gaJlPE4dSBdH6SU/jqIZGS/yo3/DSdoada0ZG6LfmAgu0s/Ls2A86sTFg+acIwx5FO/jv9ytdshV2AlBgzQGa2nQc1lDWZa+PPLvBJcg24bKKmQLy4nfqzKinJsh1ewIuS9SAGGal4cvb64o3oGDralKTxzGz0671bs6vb73/auMHkq2LVFCRT1Os0+WMaelwp3WJLuW3/EKcj8fjqvZtTyXzXQ17O/58+kKJSS7uAF0onlx0+pLwkMWyXmybmXbN3i87IJorOza8x3YW9mOSEEp5DP+FH7sfC38T2T9ipo6PWlh/WjH2TjyybQ6EGmNn0aIjvrEb7WoMF/AtFG3T3DqBEjvjimPN0x8tv0PLvk4rpqgTO3Rk4eAaYNNhPrsZQ5WHhzyrxVXa2gQl8sflA5aR+tPH76Sf0Jg1bkW5Kub4xmdKcxFzanzETlP68kiNQdxvmieSBp62oIlyw5GuudXnRZyLQCOYi/PnZhW5BO3l2mmBAyO3x9oTlXIgDJlMnSjXtkdA/ruZvvgzLYbRxdEcU6XkaEfoX9uYSxzBgpYBhkT3ZhM5bAk/Tw94UCjFgd6aC2jfHIZUh/Zg4S2WidGFmnNeuH34c59G9RhUTUEhAtyxuxNNvtRQfLmVGAR8VFlaDcRYzOtj6y+VGX4QLxJ6KrruqfjXLtkiCsjGO/qVx,iv:T2dLPyfgDM5LNvBwE/4tAAo2dHU4h489uFs42h0gTLU=,tag:r5kisT+mv0jmSODAnN94JQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1697e27xddkfkesylswayhk6ms8pln48e6nem2lrwe97yg8tenyysppqw9t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsMkt1N1FNYWN0cXF3WnFV
            ODRLUWk3SEp2VHQweWdTNWVtYmtVRGZIKzN3ClpnQlVHa1poZDZVTlNBWm9IU2F4
            RXMvaHJBbm83SGduWWcrRWR0L3JSRFkKLS0tIEVpZVZmS2dnNUpoWkNVTlQwcUR3
            SE11RzRMUG5OSFdGSXFjRzhNd3JIWFUKTujGBr5KQDfTr4fc7aLArgUZthT7gkOd
            Vhje1eOjsOS3TGLss9Qht6FRTR6LRfub178zEOGEoo9rPv7MGohvzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-20T16:57:22Z"
    mac: ENC[AES256_GCM,data:g393BV4G46NBd/1cQpBTkcEhPvFZ2JPO1yNFOaoD58lTxdr89tZBdZFbPKD4kkRihF8qlxNX5fw0o8rXSXR4v2VTWzZzPP7xwXrE5ZqViawZDYqoE7RbSW4i8QbeuOSCKE8tr5Mp1hFR162T3tWMH7Bw7xnnOqh0Mdq4pebeuPM=,iv:bDsLiF4JhKTZT2Hhv8Zdo/dCU97fjnrYTiWKw+nAs0o=,tag:4A2F8KJUSM912C//Bhu/Kw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
