apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
data:
    PUBLIC_DOMAIN: ENC[AES256_GCM,data:krTyPce0zDwLZqaNQpujdg==,iv:dsQkXeHO1a2uFReKjwdE84QqIog89tMdHR7xMppag0E=,tag:Bikjsw1X9+QvEpPjA704kg==,type:str]
    CERT_SECRET_NAME: ENC[AES256_GCM,data:50BGhpicSInd1nuLlwHd9GH6v0XzPh8f,iv:9P/emc/I3sDN4Q2H1ck/vasDUdhMGfUMApnNQ+dtD40=,tag:HDI2+zXnHwHsskEoWxHWiw==,type:str]
    WIREGUARD_CONFIG: ENC[AES256_GCM,data:UV5EiqdSfYYyXPllk8dnH2Y2UVRZAJbaPmxi0Y6pqhIINVje8IRFSChQcOw3aNV1teNJ9jgZdlFLbOFac+M02M/sFGsCn4YVZKPr8oPqgVak3yJ3gdIckdzkj2LIJb17KwBeSKjQMTMuO37/pAjG5PDpqcfOV1hNDTx2z7CwjDOXA5qSzNfnGqek7jSb22vzB2lUCwksLH9bhDK7sCmtrKQhPasS3wvAgYkbLKeuVReTu3O540CfBD2q/cJTqbMV+UKId6QBpK0QkVGgQqdLcqQdKIN33hCS3Tx0A+PQ0TjuqlAgq4GtDVUz52JmrRzK05XqEpQ0+WzbrVXbtRnEyPwv39Pm7DCa+XdsxafMHQx0PZvcRlYHtJimENM1kt/NwbqPitIF0QhWp2KZE9zHAJ8dPUX03yfhHK/MuKwjQKs8LtBduH2ixJm2zbj6rU7N/SSc2wMKfu1yBfH1sIU2UtduuL8dOizLrxlDUSn5vnn2vxUGz2/n16qQjJqNEPVLE3WX9eZ6PCblf8PP9soYvJZnvEHNBbzH18Yx1MGlFtynn+4Lr0ZpOsT/KbG6Jf3BLDdBemUSc3lWyDQf1J76YqW2uFFfdUwCVh31RWYLTCIIMB+iWDc+2/FxuHNqv4bC5j1DFaUMFYRjbRg/KhssZns2BkmDQ15N9EihBoGo7/2Onpl91NtHIyLz/J3X3/xj+GpSQnf1UdU6Z2YrL23mY+VSn17xIP2L14fDtd0ENv+RVYyYZxZY9OkH0OCHXslYBjNsmcLx+7gNdeo9a9oiQQ/lE12e70XGomML32eMBbChy6IEin8RU0xmWeigQ8vcGfpi7tzzS1ROiWYpkpoBlymPKcA+BRc7ne7k08ZOYZ2uNuUARA5UmnfLlwG8ubvypXihi0pQUX3DgCsFcv9I+w30TZDZIg6Rp4MDOqAMo/F/70ukOmEFjDbxgM+sdJ7HseYROJb2g6WN77HxHPVqTAz7b5pZSZfpebjHPHVDc0IrftbYYqQ/0gApIkbP3W+5WBIsePlIWlg3kXGRuej8r0N9cRurCDXWs70bdrFFeqH/F0phO4SeDm8OiUPjKLrSB36k+0IpgwJMBySv6mBvdKBOqlbWigX+kUzqV9ayr81GZiTXdjcvrc/jCphs+S/4ebtKhlrYBs958Qw5WksiViqoNxfls93kQps/cvXSOsYXixvM0X8R4eiLPekmpsJztfQZ7jGSVl0ri5IIuuHVQk76KtFAZUe2M+BWondX7W9y6BNkJ5C4GHquwYrVFOqyagarNlh6yVdmZeUQYzSluFZwOdrw1Ahygyj5+vD+6xrnKST422/lwVjCXIJHcielzfJH0RuglRYtHgc2o5dpB92aeT1Jaen7l2ug5ufhGB66J+Bs1jvf9vlrLm3/3kMAQZg3jCspXi9LK9L5RVPmwPQl7EYPgKlbnc/XBhFjuguoYrOESIdlC9E4kLyifAbefn06oShn0QZNQYpg73xuOzWET3r6ItH2KQi4jv8PMGAItGvMr21waWsaocOQYKyF6yzMfhL94scR3baATvfU1kkXfoGzB1ncgCTK7AmtBpcDtAAwpN9j8tQKwhp1kSedwttKY9vpBhFRKMY2qxPHE7NYh9tXZ5xyQaTf8A==,iv:l1dUYfMTbHIP6xt47gpWQ93dQpzCZo/zoEcqp5vS8qQ=,tag:uWbUkW/VSlHOcF5igTiaUg==,type:str]
    VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:C+pJ/Y6rVMkPMOwgI4zSNyVTRqltiaKJr14a18E4iyp4xnGupDKKaM1RP4t1wTTsQLF/qEEbRieYraDg+wDtWR8p+fg0tRU66Jh4K4lPE9KAoNTWuwV5/g==,iv:v518O9ojvqYFe5v+YsEbpSbNKABWgQECiWtQ6+myRcs=,tag:4AOVNchgKBRpvr3f490I8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1697e27xddkfkesylswayhk6ms8pln48e6nem2lrwe97yg8tenyysppqw9t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiYTRKT3VvTnQ2dmppTUJZ
            Uk5ZdU9tNitrQW80SG16WE5vNkhlaE1XTXpzCnFrOUc3VHNHQ3Jmd2lnY3gzTXJ3
            Mk56aE9HUC9NdWRtTVJJNjQva2lLbFEKLS0tIFRRNkxYNm5yQ1Q1cDQwcG5hZDZM
            QXl4aUxheE9KdmFXVEE4bDRHWDQwVHcKgtDUV4UCj0dMUBuyYivmJvOOjl9Aok6F
            2fI5CGS2RG9bJWSSgaJsty8ea/53BIbINPzaoWPYlqTw7ySe3OXKHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-27T10:47:34Z"
    mac: ENC[AES256_GCM,data:M41oL9yM/PXKkmeecM6QM4J2mPP54IK+Zrt815TisTb4Sm6WljMYbGhTgCSIVj7q3+NBfuXCRvHwt7ECYFXRuMT7i2L0/tq7xFEPKfULYdzhBoW0uTP1KMK6IrCWI9Fe8eG6KQmgKw6+5TGVqw0JQE69FPKc21eCln2eoViWp88=,iv:593q0xZBoCHa1nn57SaU1oFgBx/OPMKb1kceJtgsIPY=,tag:tdcbiK//DiBRfmoJJNo0tg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
