---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: flux-system
data:
  TIMEZONE: Asia/Kolkata
  NFS_SERVER: 192.168.0.225
  PHOTOPRISM_DATABASE_SERVER: mariadb.databases.svc.cluster.local:3306