apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
data:
    PUBLIC_DOMAIN: ENC[AES256_GCM,data:W1pL9zWk9GtgeV+7xZjaQQ==,iv:/6f0kILnIoi8DkeBrnWApvvRdTbPLg5A02wUpv+OTXY=,tag:EA+u2O12GkH76JKgwtRsBg==,type:str]
    CERT_SECRET_NAME: ENC[AES256_GCM,data:K+9OXDjQbH+yVbnhcFUQjZC4o4MGyQFe,iv:Qoax4iwt3iKd6+1HN6uleHZOtSK4GQEASfCaa2ydBMw=,tag:+B4rY07XQdbrSL0gTzYQhA==,type:str]
    WIREGUARD_CONFIG: ENC[AES256_GCM,data:QbQarlFR9CTkaoucFjTCP1SFdGirnoCFHtz5uPjyaxy/s5rm3MDrx/iM28g7OWFsSRt6lIoULDTQ/RnBwd+bv8BNvsZXKLReLupHBkcK4u/4DptLOHtmJP6bDiWV+M509ja4HE3ZpW5GuN6bZUgybZA3O7vuQZhWGDiScQCuKhMgyPcc6i4sFjRS4uwchNhLDpWrj2UOyqWi6c6htCwwzagwzssl+sYQe2V7ZkcYv/r47rN5LjJ6fshwPLKg+OuH4zH8j2uNV59HE+BwkgapJD69Tf0TJZNn7IwuYRTgJe97VA+1B5t/KgqSnMIpLsLgd0rKPeLuiByZDli5Lrgz7y3SS77e67I9UZKcLTpWY4a4Bp/YpmpWRp8DMi1sorBASSI91Sp1Cr1JkTav/13obkSGdqARnFumkSh1oKyCxmzMFdzuN6D5DT++SEj0V2hkdsqdRGeMf0Y475zpWrQ7LiTfbBntqfRKrNpqFWk5D1gD41RPcrPZ/FjOO+hlJvDhg+UBq97Lzp4WlbZxP4SC+MgTP4tu0d6ONwNBqpAQbJiXHJ7RfmrpigDpLi+8CLMawlMgzN87/tQeJhdCgv2hPSjdtaKi291qqX9TI06WOLv4VMc3ugFUq7XC8YM0D8NrWVXet/ugGA9XScckFauQjjF6AEPIZsaAtXsG2+SvkjT5PgDPNAyys77Fg9iqfLTW96UtZvHoN0P7QL4S/E+laMHY/VCGYE8O5zkDY5pISC7psmuCwUCEda2BVPOlKSwzMchdWdmx/hZF9fWbDuCHdh5d29ucywJ1ZIAMn2afPNUYxEJShH3mwnRnm9O+Q4JutB0GvKa50O4Q8PlHbx7HrIG8Pu287t0XtWdG591ZMwJONyw4jBx9AS4Gbbj/nDUFRcxcR50Q2qP6FBDp3tgfr/RBEg9Vj/sy3O7knIYN1p6eZYC7NMv0m+9+yOgJ3HE2z8Dqth2rhHBfJsPAoZQ09e4zvHmpxCc+5/wZQ3KN7ToFJcjq76pK37CVUI0eyEO+oHEzhRAuJIa4xkhGwmMiw3WGwHVzuXr2nYezi0GPSprpjnhyjcaaen0qqX6GDsry6++mqQm/o4Z566LVvvde5aFNETbEBWMcxFhdpVhG0mp2Qr2wams1jcao+WEVeVFfbL5Zljq3oFqvX6wUsVBGoQWucYoGojLce0KZaN/MkTSuzqJOZAwDXvvhxXNQ/m8zRQf9RngPULPRs8NPWuZXHeM+OEEWCu3iHhimajBjE1vZBXfufI3f6XyaoJ2TWcuX6Wp8Kw3Fbohh0zPePCw552xQpqd2ynmsF4bMAoX0xm0aUeNkHOqCwEwtIaqFwwSpWt4HKCJ+iik6CNhAjG8ztgKpY0+aDJi8rl92dkzJWgfGFzvKde25bug+BSjutM48f7L3np6woXPsPNyUxcqD00G7zpX1SY+fC+fvXGrKV5ml+PWDJalSV6X0cKSmUbOWUoSTr9oCIxs/vh3l,iv:fCK95BcgI2Rx5H6cDLo7Be5+dzBE1kcTDvy+RqoRN9E=,tag:MJEpTAQ+e6EkfHejMTiMOg==,type:str]
    VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:nroeKk/bxtjaae3E7jL5703RNvHtfZ7hg2yBzETTTFdh4i7bUOEdTD8yBtI00AxSePyR2xlyJdXWfKWF49JXYNav2WgWSOztxYKSzhF2/PuCTuWjeh3P1g==,iv:3fo06h/2b1zbrfcXFeFDfbPBMaC+1vTlqktHO+t5HQ8=,tag:8A7XuLNtmF9EqiYwpVyRig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1697e27xddkfkesylswayhk6ms8pln48e6nem2lrwe97yg8tenyysppqw9t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkOGxjN1Q4U1pkVWhKL0Jy
            NHRZcDdHWFp1RWM3SXhpRDJaSWd3TXVmdnhVCnJBN2lVNlpoRFN6L1RrWGRpY1BR
            MkU3QlV6OTlzNEhiaTlLNFNsTHMyUGsKLS0tIE9pT2JIcUtqK0YzNUpUeG1PK2Zw
            Q0ttdXg4S2Q0WWs3R0VJVlRsOUsvNjQKvsOHOYmn6+TPqZg2D4kWRvUugPPSVB4i
            yzVPrCNoxyMKz7L64tK2M4zMAyIx77dCOc4AuvjRo/10469wCFrTkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-22T08:14:06Z"
    mac: ENC[AES256_GCM,data:v/IbH+da5QWnMCi8eBhLX4DcMmO0YDOEptnyte46+OWXtkEj/BJAU4kSJjAQWoi0hGg2m1EORwZZKg9ITSqySJoHxurooT0BUHxw4+XP0Emy8pZrJ/AJBYAFZz6gFur5k9pgpIZaz+AToB6M4bl/Zv1q0v0y0WlbsHzx/X3A9I0=,iv:VE86NO7ksBgCGb1R5KOWiFNWKheOxQbt44mzRysyBog=,tag:lZTgtkCOb3xrd/a4Em4zjw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
