apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
data:
    PUBLIC_DOMAIN: ENC[AES256_GCM,data:ItyzcFpL9GDu4ElOPySLgA==,iv:8j/9tdtQtvU3j4RW+b51+BR4LRNw3VpoMpb7oP2W7RI=,tag:5djQFxTxE2i0vWyETEYv+w==,type:str]
    CERT_SECRET_NAME: ENC[AES256_GCM,data:11l1w5mRzx/34aOsZ2tzirHww/f83CrK,iv:1WKPoPm0qXcRyhh3etm62ix5V9u90ZEqEzsRdTNApsM=,tag:iNVBxQmLa2ZhYJN/w+kE/w==,type:str]
    WIREGUARD_CONFIG: ENC[AES256_GCM,data:SrVEVlx9e2SwTXlyPbr+qqx7+GSOATF/bKLVc8FkPB0y8PKKdxgsueMP6jhe1Wprvjs68x+C3c/abo1zBnXxYkQMx+L5/5+wfsc3bfxpl25x/T4YliyrJ9CXIf9ElI1Wd9zT4j0wFMH8XhKdOcm/nrvUJvvGM3Rt5DoACS9ZBsGAqzk8lTxCNQoy/O6FV0ytgmL/e2BQVoSaYQ6ztp840BVUjdHgov3kqXcLmJBtaZqFhmIg8/7WCPodZ0FjVevZ9y1Rs4r53PTxok1VAJF4UuYXa9Ku8F1Y0JJUCIIKqhBreieCCAhYFZ0mQkV1x/85A5EJZv4pyjnYZdeMKGR7vlHPFRlwiuvI3YehL93dZBQOvDHTx3NrT8hwQRxj+JFJr6Q4LpZjbnlbTpE5uv/3jN/iw4Xmr9zoK+f+oluWBViSBI2zgO3m/0JcZJhwgOzQQ8rSjhIv+z1O/zrA7P+9lomHk0djoFCx/sjT7bkeY7xruHqdejZZVBXM13z1f+BZJEASbGD3CQ3GX/88EyiGLTH8hSqlHPmC+A/BxlbDZ2Rzbrv8H7dZtNda8+gRpYn6tyzt6sF/GywCu6vO+zPTWd2nbf4y7mEjRLw791GSwgf8M0YYkkAJ4v5uasqtQqqrk9kNVtdmMazlRn/3/QGX3Qtva1JRA3PVXD1ufXKoO9+PhxZxKBceiwNGydpnICfCDMIJ8ZdyKyEulxP2AD0OfhgVL86haDAPwzP3J42Se0Aubi0wrS2enSJ98pQaokPBW2Mx+Fhmc4OFzSjdB5b0Szoax12aQnL7ZXrL/vaUEbBV0//wHgzTEwxi//vmANgd7MVy3rfw2tpQOC7iXiQ4W/QCrdCN7eOPMg5nTvwoCl4iTq7t+KksVmWf+oBKppUHacqnVHZ5RL7m3TuTTeuXUjyzw8Un9x8L8n70dHU/gdLtj4g+C71Z5pZ34uHkDDTyTPA41MFj+Q1idrqVD+Q75sdLpYpROSHvxshzxrslB8ZOuDWgnxXH6JOPG4hKQ1sckR5FrjseJFbZZFz/plC1hbmLU4Y0eES/Jka0n55f/X1lMSoaT/sVo6YtlDVuHNtYsny+EMC2IMXbmpULTaro+0RX+Xq2AhVoRh8UaIzecQ4vHahPT6u27sdwSQ4OHESVLnGyg91ii/ABgiaH4rCIwXjoAxobfq5qJGri1dGaU/a7nAyCwmwjcljHsXeH3tcG7v/EzwDoUz2mMMGgG/DhFnIH+eBs/jIMOybucV0Bq1F3MbPSaOVrBDlKomc6mdTGXN9YNEkztqB3SEs6JVTPDsgjbKFzruhkwdGLZa3uyEvjNBp7MzkjDjS2Wi1OrUHuRE2aoE1H0Px9vmxwJgIywquJAd+E9xyv3dEst3ZIa6Cvjj9k4uz/pCxTiDigGfwqQZleD+/ebMaelEPMdEPTNyGeRwWQUGqp1YcJibC1yev2KsxjBch/jCy4VmA9H7dqbH6qeLKxXAUvEfYZnERHuqfzjSv60r8aqsdG1v7dKsv+N8YiE2g/uV2EG3kAIEO+bIGaxUZY3X2L7TNMvFDOyFvcgyjzvchFiJI0w+Xy8vT64yj2okvUQmWVRYtx7Hn+CEs21fPMukDgPIECpsCRQ0oKpix0KX2junGmCm5kBMc=,iv:vinw6yASLkxRfvtQEMzpOnccUPLW7FvTCMwjHTIgRaU=,tag:EE3a5RAsMHT66337fYI37A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1697e27xddkfkesylswayhk6ms8pln48e6nem2lrwe97yg8tenyysppqw9t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPOHQ5QXVNYTRhb1d1bDIv
            UjhMdWN1elpSQzkyUDByL3FPaXVMZHc2c3dzCnF2a2d4M05uenc3aTFDUmc1TkJ5
            TWUzNVl6SlI0b1BvZmNhdDZZcnFwMG8KLS0tIDYwNmRzOVp1SVJWVUcvT1h3UTN5
            RFY4M2xJV1FqY0hyWGI0STdtTmI1WUkKN+TFTXM7H1NNLfmvokTjdzMLiqZyPgEc
            rmZVOM4rAFjKql8U7wHksHf+B92Yqbn5qypjfaTrCOvMujqLjBFvFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-21T19:33:11Z"
    mac: ENC[AES256_GCM,data:F4Cww2hFNLJPFXNHVE9M5pvIDD0FYtW3Wx7SqgCSnY2/GC2526W/XK4pDvAHMhoIdiVofVhzdPiMZGhvzxUIKw4XkJ8ctuqcQjpYc31SV0RMmP5lAfa0JXKg6h9p0KkgWAbNf6fAW0TVnd7tc90JgZxLbtsIVVVCS9fsxWaD15c=,iv:OG6yhqxHQPOSs7vEgcsWz+8mbx1EGsQoHvl2ybCi3QY=,tag:qT2FJ9dXuQM+aTAbZGjBEw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
