apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: reflector
spec:
  releaseName: reflector
  chart:
    spec:
      chart: reflector
      version: "9.1.12"
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3