apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - k8s-at-home.yaml
  - netdata.yaml
  - jetstack.yaml
  - ingress-nginx.yaml
  - wg-easy.yaml
  - bjw-s.yaml
  - intel.yaml
  - bitnami.yaml
  - nextcloud.yaml
  - immich.yaml
  - goauthentik.yaml
  - cnpg.yaml
