apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel-device-plugins-operator
  namespace: intel
spec:
  releaseName: intel-device-plugins-operator
  chart:
    spec:
      chart: intel-device-plugins-operator
      version: "0.31.1"
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3