apiVersion: v1
kind: Service
metadata:
  name: adguard
  namespace: external-ingresses
spec:
  ports:
    - name: app
      port: 443
      protocol: TCP
      targetPort: 443
  clusterIP: None
  type: ClusterIP

---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: adguard-es
  namespace: external-ingresses
  labels:
    kubernetes.io/service-name: adguard
addressType: IPv4
ports:
  - name: app
    port: 443
    protocol: TCP
endpoints:
  - addresses:
    - "${DNS_SERVER}"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: adguard-doh
  namespace: external-ingresses
spec:
  hostnames:
    - adguard.${PUBLIC_DOMAIN}
  parentRefs:
    - name: c0depool-gateway
      namespace: gateways
  rules:
    - backendRefs:
      - name: adguard
        port: 443
      matches:
      - path:
          type: PathPrefix
          value: /dns-query
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: adguard
  namespace: external-ingresses
spec:
  hostnames:
    - adguard.internal.${PUBLIC_DOMAIN}
  parentRefs:
    - name: c0depool-gateway
      namespace: gateways
  rules:
    - backendRefs:
      - name: adguard
        port: 443
      matches:
      - path:
          type: PathPrefix
          value: /
---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: adguard-tls-policy
  namespace: external-ingresses
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: adguard
  validation:
    hostname: adguard.${PUBLIC_DOMAIN}
    caCertificateRefs:
      - name: internal-ca
        kind: Secret
        group: ""