apiVersion: v1
kind: Service
metadata:
  name: adguard
  namespace: external-ingresses
spec:
  ports:
    - name: app
      port: 443
      protocol: TCP
      targetPort: 443
  clusterIP: None
  type: ClusterIP

---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: adguard-es
  namespace: external-ingresses
  labels:
    kubernetes.io/service-name: adguard
addressType: IPv4
ports:
  - name: app
    port: 443
    protocol: TCP
endpoints:
  - addresses:
    - ip: ${DNS_SERVER}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adguard
  namespace: external-ingresses
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  rules:
  - host: &host adguard.${PUBLIC_DOMAIN}
    http:
      paths:
      - path: /dns-query
        pathType: Prefix
        backend:
          service:
            name: adguard
            port:
              number: 443
  tls:
    - secretName: "${CERT_SECRET_NAME}"
      hosts:
        - *host