apiVersion: v1
kind: Service
metadata:
  name: adguard
  namespace: external-ingresses
spec:
  ports:
    - name: app
      port: 443
      protocol: TCP
      targetPort: 443
  clusterIP: None
  type: ClusterIP

---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: adguard-es
  namespace: external-ingresses
  labels:
    kubernetes.io/service-name: adguard
addressType: IPv4
ports:
  - name: app
    port: 443
    protocol: TCP
endpoints:
  - addresses:
    - "${DNS_SERVER}"
---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: adguard
#   namespace: external-ingresses
#   annotations:
#     nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
# spec:
#   ingressClassName: nginx
#   rules:
#   - host: &host-public adguard.${PUBLIC_DOMAIN}
#     http:
#       paths:
#       - path: /dns-query
#         pathType: Prefix
#         backend:
#           service:
#             name: adguard
#             port:
#               number: 443
#   - host: &host-private adguard.internal.${PUBLIC_DOMAIN}
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: adguard
#             port:
#               number: 443
#   tls:
#     - secretName: "${CERT_SECRET_NAME}"
#       hosts:
#         - *host-public
#         - *host-private
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: adguard-doh
  namespace: external-ingresses
spec:
  hostnames:
    - adguard.${PUBLIC_DOMAIN}
  parentRefs:
    - name: c0depool-gateway
      namespace: gateways
  rules:
    - backendRefs:
      - name: adguard
        port: 443
      matches:
      - path:
          type: PathPrefix
          value: /dns-query
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: adguard
  namespace: external-ingresses
spec:
  hostnames:
    - adguard.internal.${PUBLIC_DOMAIN}
  parentRefs:
    - name: c0depool-gateway
      namespace: gateways
  rules:
    - backendRefs:
      - name: adguard
        port: 443
      matches:
      - path:
          type: PathPrefix
          value: /
---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: adguard-tls-policy
  namespace: external-ingresses
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: adguard
  validation:
    hostname: adguard.${PUBLIC_DOMAIN}
    caCertificateRefs:
      - name: internal-ca
        kind: Secret
        group: ""