apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: external-ingresses
spec:
  ports:
    - name: app
      port: 8123
      protocol: TCP
      targetPort: 8123
  clusterIP: None
  type: ClusterIP

---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: home-assistant-es
  namespace: external-ingresses
  labels:
    kubernetes.io/service-name: home-assistant
addressType: IPv4
ports:
  - name: app
    port: 8123
    protocol: TCP
endpoints:
  - addresses:
    - "${HA_SERVER}"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant
  namespace: external-ingresses
spec:
  ingressClassName: nginx
  rules:
  - host: &host ha.${PUBLIC_DOMAIN}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: home-assistant
            port:
              number: 8123
  tls:
    - secretName: "${CERT_SECRET_NAME}"
      hosts:
        - *host