apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: external-ingresses
spec:
  ports:
    - name: app
      port: 8123
      protocol: TCP
      targetPort: 8123
  clusterIP: None
  type: ClusterIP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: home-assistant-es
  namespace: external-ingresses
  labels:
    kubernetes.io/service-name: home-assistant
addressType: IPv4
ports:
  - name: app
    port: 8123
    protocol: TCP
endpoints:
  - addresses:
    - "${HA_SERVER}"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: home-assistant
  namespace: external-ingresses
spec:
  hostnames:
    - ha.${PUBLIC_DOMAIN}
  parentRefs:
    - name: c0depool-gateway
      namespace: gateways
      sectionName: https
  rules:
    - backendRefs:
      - name: home-assistant
        port: 8123
      matches:
      - path:
          type: PathPrefix
          value: /
---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: home-assistant-tls-policy
  namespace: external-ingresses
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: home-assistant
  validation:
    hostname: ha.${PUBLIC_DOMAIN}
    caCertificateRefs:
      - name: internal-ca
        kind: Secret
        group: ""