apiVersion: v1
kind: Service
metadata:
  name: openmediavault
  namespace: external-ingresses
spec:
  ports:
    - name: app
      port: 443
      protocol: TCP
      targetPort: 443
  clusterIP: None
  type: ClusterIP

---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: openmediavault-es
  namespace: external-ingresses
  labels:
    kubernetes.io/service-name: openmediavault
addressType: IPv4
ports:
  - name: app
    port: 443
    protocol: TCP
endpoints:
  - addresses:
    - "${NFS_SERVER}"

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: openmediavault
  namespace: external-ingresses
spec:
  hostnames:
    - omv.internal.${PUBLIC_DOMAIN}
  parentRefs:
    - name: c0depool-gateway
      namespace: gateways
      sectionName: https
  rules:
    - backendRefs:
      - name: openmediavault
        port: 443
      matches:
      - path:
          type: PathPrefix
          value: /
---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: openmediavault-tls-policy
  namespace: external-ingresses
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: openmediavault
  validation:
    hostname: omv.internal.${PUBLIC_DOMAIN}
    caCertificateRefs:
      - name: internal-ca
        kind: Secret
        group: ""