apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arr-stack
  namespace: arr-stack
spec:
  releaseName: arr-stack
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
