apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: databases
spec:
  releaseName: cloudnative-pg
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.24.0"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
   config:
      clusterWide: false