apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
spec:
  releaseName: redis
  chart:
    spec:
      chart: redis
      version: "18.6.1"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    global:
      storageClass: "longhorn"
      redis:
        password: "${REDIS_AUTH}"
    master:
      initContainers:
        - name: repair-redis
          image: docker.io/bitnami/redis:7.2.3-debian-11-r2
          command: ['sh', '-c', 'redis-check-aof --fix  /data/appendonly.aof']
    replica:
      initContainers:
        - name: repair-redis
          image: docker.io/bitnami/redis:7.2.3-debian-11-r2
          command: ['sh', '-c', 'redis-check-aof --fix  /data/appendonly.aof']