apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  releaseName: authentik
  chart:
    spec:
      chart: authentik
      version: "2025.12.4"
      sourceRef:
        kind: HelmRepository
        name: goauthentik
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    authentik:
      secret_key: "${AUTHENTIK_KEY}"
      error_reporting:
        enabled: false
      postgresql:
        password: "${AUTHENTIK_DATABASE_PASSWORD}"
    server:
      route:
        main:
          enabled: true
          kind: HTTPRoute
          hostnames:
            - auth.${PUBLIC_DOMAIN}
          parentRefs:
            - name: c0depool-gateway
              namespace: gateways
    postgresql:
      enabled: true
      auth:
        password: "${AUTHENTIK_DATABASE_PASSWORD}"
      primary:
        persistence:
          size: 8Gi
          storageClass: longhorn
    redis:
      enabled: true
      master:
        persistence:
          size: 1Gi
          storageClass: longhorn