apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wireguard
  namespace: wireguard
spec:
  releaseName: wireguard
  chart:
    spec:
      chart: wireguard
      version: "1.4.2"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/c0depool/wireguard
      tag: v1.0.20210914
    env:
      TZ: "${TIMEZONE}"
      #IPTABLES_BACKEND: nft
      #KILLSWITCH: false
    service:
      main:
        enabled: false
    probes:
      liveness:
        enabled: false
    #securityContext:
    #  capabilities:
    #    add:
    #    - NET_ADMIN
    #    - SYS_MODULE
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        mountPath: "/etc/wireguard/wg0.conf"
        subPath: "wg0.conf"
        type: "custom"
        volumeSpec:
          secret:
            defaultMode: 0600
            secretName: wireguard-config
