apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: wireguard
  namespace: wireguard
spec:
  releaseName: wireguard
  chart:
    spec:
      chart: app-template
      version: "1.4.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/c0depool/wireguard
      tag: v1.0.20210914
      pullPolicy: Always
    env:
      TZ: "${TIMEZONE}"
      IPTABLES_BACKEND: nft
      KILLSWITCH: false
    service:
      main:
        enabled: false
    probes:
      liveness:
        enabled: false
    securityContext:
      fsGroup: 1000
      capabilities:
        add:
        - NET_ADMIN
        - SYS_MODULE
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        mountPath: "/etc/wireguard/wg0.conf"
        subPath: "wg0.conf"
        type: "custom"
        volumeSpec:
          secret:
            defaultMode: 0600
            secretName: wireguard-config
