apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wireguard
  namespace: wireguard
spec:
  releaseName: wireguard
  chart:
    spec:
      chart: app-template
      version: "1.3.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/k8s-at-home/wireguard
      tag: v1.0.20210914
    env:
      TZ: "${TIMEZONE}"
    service:
      main:
        enabled: false
    probes:
      liveness:
        enabled: false
    configSecret:
      enabled: true
      config: "${WIREGUARD_CONFIG}"
