apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wireguard
  namespace: wireguard
spec:
  releaseName: wireguard
  chart:
    spec:
      chart: app-template
      version: "3.7.3"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/c0depool/wireguard
              tag: v1.0.20210914
              pullPolicy: Always
            env:
              TZ: "${TIMEZONE}"
              IPTABLES_BACKEND: nft
              KILLSWITCH: false
            probes:
              liveness:
                enabled: false
            securityContext:
              fsGroup: 1000
              capabilities:
                add:
                  - NET_ADMIN
                  # - SYS_MODULE

    persistence:
      config:
        enabled: true
        globalMounts:
          - path: "/etc/wireguard/wg0.conf"
            subPath: "wg0.conf"
            readOnly: true
        type: "custom"
        volumeSpec:
          secret:
            defaultMode: 0600
            secretName: wireguard-config
