apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: intel-device-plugins-gpu
  namespace: intel
spec:
  releaseName: intel-device-plugins-gpu
  chart:
    spec:
      chart: intel-device-plugins-gpu
      version: "0.29.0"
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3