apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: filebrowser
  namespace: filebrowser
spec:
  chart:
    spec:
      chart: app-template
      version: "2.4.0"
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: filebrowser/filebrowser
              tag: v2.26.0
            env:
              TZ: "${TIMEZONE}"
    service:
      main:
        ports:
          http:
            port: 80      
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        size: 1Gi
        retain: true
        accessMode: ReadWriteOnce
      data:
        enabled: true
        type: nfs
        server: "${NFS_SERVER}"
        path: /mnt/ext-hdd/media/
        accessMode: ReadWriteOnce
    ingress:
      main:
        enabled: true
        className: nginx
        annotations: 
          nginx.ingress.kubernetes.io/proxy-body-size: 5120m
        hosts:
          - host: &host "files.${PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:            
                  name: main
                  port: http
        tls: 
          - secretName: "${CERT_SECRET_NAME}"
            hosts:
            - *host