apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: filebrowser
  namespace: filebrowser
spec:
  chart:
    spec:
      chart: app-template
      version: "2.4.0"
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: filebrowser/filebrowser
              tag: v2.27.0
            env:
              TZ: "${TIMEZONE}"
    service:
      main:
        ports:
          http:
            port: 80
    configMaps:
      settings:
        enabled: true
        data: 
          .filebrowser.json: |
            {
              "port": 80,
              "baseURL": "",
              "address": "",
              "log": "stdout",
              "database": "/config/database.db",
              "root": "/srv"
            }
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        size: 1Gi
        retain: true
        accessMode: ReadWriteOnce
      filebrowser-settings:
        enabled: true
        type: configMap
        name: filebrowser-settings
        advancedMounts:
          main:
            main:
              - path: /.filebrowser.json
                subPath: .filebrowser.json
      data:
        enabled: true
        type: nfs
        server: "${NFS_SERVER}"
        path: /mnt/ext-hdd/media/
        accessMode: ReadWriteOnce
        globalMounts:
          - path: /srv
            readOnly: false
    ingress:
      main:
        enabled: true
        className: nginx
        annotations: 
          nginx.ingress.kubernetes.io/proxy-body-size: 5120m
        hosts:
          - host: &host "files.${PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:            
                  name: main
                  port: http
        tls: 
          - secretName: "${CERT_SECRET_NAME}"
            hosts:
            - *host