apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ha
  namespace: ha
spec:
  chart:
    spec:
      version: ">=1.0.0"
  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      pullPolicy: IfNotPresent
      tag: 2023.2.3
    env:
      TZ: Asia/Kolkata
    persistence:
      config:
        enabled: true
        storageClass: longhorn             
  valuesFrom:
    - kind: Secret
      name: ha-secrets
      valuesKey: ha-secrets.yaml
      optional: true