apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jellyseerr
  namespace: jellyseerr
spec:
  chart:
    spec:
      chart: app-template
      version: "2.4.0"
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: fallenbagel/jellyseerr
              tag: 1.7.0
            env:
              TZ: "${TIMEZONE}"
    service:
      main:
        ports:
          http:
            port: 5055      
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        retain: true
        accessMode: ReadWriteOnce
        globalMounts:
          - path: /app/config
            readOnly: false
    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: &host "jellyseerr.${PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:            
                  name: main
                  port: http
        tls: 
          - secretName: "${CERT_SECRET_NAME}"
            hosts:
            - *host