apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  chart:
    spec:
      chart: app-template
      version: "1.4.0"
  values:
    image:
      repository: jellyfin/jellyfin
      tag: 10.8.10
    env:
      TZ: "${TIMEZONE}"
    service:
      main:
        ports:
          http:
            port: 8096      
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        accessMode: ReadWriteOnce
      media:
        enabled: true
        type: nfs
        server: "${NFS_SERVER}"
        path: /mnt/ext-hdd/media/
        accessMode: ReadWriteOnce
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - 
            host: &host "jellyfin.${PUBLIC_DOMAIN}"
            paths:
              -
                path: /
                pathType: Prefix
                service:            
                  name: jellyfin
                  port: 8096
        tls: 
          - secretName: "${CERT_SECRET_NAME}"
            hosts:
            - *host  
    # podSecurityContext:
    #   runAsUser: 568
    #   runAsGroup: 568
    #   fsGroup: 568
    #   # Hardware acceleration using an Intel iGPU w/ QuickSync
    #   # These IDs below should be matched to your `video` and `render` group on the host
    #   # To obtain those IDs run the following grep statement on the host:
    #   # $ cat /etc/group | grep "video\|render"
    #   # video:x:44:
    #   # render:x:109:
    #   supplementalGroups:
    #   - 44
    #   - 106
    # resources:
    #   requests:
    #     # Hardware acceleration using an Intel iGPU w/ QuickSync and
    #     # using intel-gpu-plugin (https://github.com/intel/intel-device-plugins-for-kubernetes)
    #     gpu.intel.com/i915: 1
    #     cpu: 200m
    #     memory: 256Mi
    #   limits:
    #     # Hardware acceleration using an Intel iGPU w/ QuickSync and
    #     # using intel-gpu-plugin (https://github.com/intel/intel-device-plugins-for-kubernetes)
    #     gpu.intel.com/i915: 1
    #     memory: 4096Mi
    # nodeSelector:
    #   intel.feature.node.kubernetes.io/gpu: "true"