apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  chart:
    spec:
      chart: app-template
      version: "3.0.4"
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: jellyfin/jellyfin
              tag: 10.8.13
            env:
              TZ: "${TIMEZONE}"
              JELLYFIN_CACHE_DIR: /config/cache
            resources:
              requests:
                # Hardware acceleration using an Intel iGPU w/ QuickSync and
                # using intel-gpu-plugin (https://github.com/intel/intel-device-plugins-for-kubernetes)
                gpu.intel.com/i915: 1
                cpu: 400m
                memory: 1Gi
              limits:
                # Hardware acceleration using an Intel iGPU w/ QuickSync and
                # using intel-gpu-plugin (https://github.com/intel/intel-device-plugins-for-kubernetes)
                gpu.intel.com/i915: 1
                memory: 4Gi
            probes:
              liveness:
                enabled: true
                custom: true
                type: exec
                spec:
                  initialDelaySeconds: 20
                  periodSeconds: 20
                  timeoutSeconds: 5
                  failureThreshold: 3
                  exec:
                    command:
                      - /bin/bash
                      - -c
                      - "curl http://localhost:8096/health --fail"
    service:
      main:
        controller: main
        ports:
          http:
            port: 8096      
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        size: 15Gi
        retain: true
        accessMode: ReadWriteOnce
      media:
        enabled: true
        type: nfs
        server: "${NFS_SERVER}"
        path: /media/
      media-zurg:
        enabled: true
        type: hostPath
        hostPath: /mnt/media_zurg/
        globalMounts:
          - path: /media-zurg
            readOnly: true
    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: &host "jellyfin.${PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:            
                  identifier: main
                  port: http
        tls: 
          - secretName: "${CERT_SECRET_NAME}"
            hosts:
            - *host
    defaultPodOptions:
      nodeSelector:
        intel.feature.node.kubernetes.io/gpu: "true"
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        supplementalGroups:
          - 44
          - 105