apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
  # - ../base/jellyfin
  - ../base/filebrowser
  - ../base/vaultwarden
  # - ../base/nextcloud
  - ../base/c0depool-blog
patchesStrategicMerge: 
  # - jellyfin-values.yaml
  - filebrowser-values.yaml
  - vaultwarden-values.yaml
  # - nextcloud-values.yaml
  - c0depool-blog-values.yaml