apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
  - ../base/jellyfin
  - ../base/jellyseerr
  - ../base/filebrowser
  - ../base/vaultwarden
  - ../base/nextcloud
  #- ../base/babybuddy
  # - ../base/photoprism
  #- ../base/home-assistant
  #- ../base/plex  
patchesStrategicMerge: 
  - jellyfin-values.yaml
  - jellyseerr-values.yaml
  - filebrowser-values.yaml
  - vaultwarden-values.yaml
  - nextcloud-values.yaml
  #- babybuddy-values.yaml
  # - photoprism-values.yaml
  #- ha-values.yaml
  #- plex-values.yaml