apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  chart:
    spec:
      chart: nextcloud
      version: "6.6.3"
  values:
    image:
      repository: nextcloud
      tag: 30.0.5-fpm-alpine
    ingress:
      enabled: true
      className: nginx
      annotations: 
        nginx.ingress.kubernetes.io/proxy-body-size: 4G
        nginx.ingress.kubernetes.io/disable-proxy-intercept-errors: "true"
        nginx.ingress.kubernetes.io/custom-http-errors: "404,415"
        nginx.ingress.kubernetes.io/default-backend: "nextcloud"
        nginx.ingress.kubernetes.io/server-snippet: |-
          server_tokens off;
          proxy_hide_header X-Powered-By;
          rewrite ^/.well-known/webfinger /index.php/.well-known/webfinger last;
          rewrite ^/.well-known/nodeinfo /index.php/.well-known/nodeinfo last;
          rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
          rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
          location = /.well-known/carddav {
            return 301 $scheme://$host/remote.php/dav;
          }
          location = /.well-known/caldav {
            return 301 $scheme://$host/remote.php/dav;
          }
          location = /robots.txt {
            allow all;
            log_not_found off;
            access_log off;
          }
          location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
            deny all;
          }
          location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
            deny all;
          }
      tls:
        - secretName: "${CERT_SECRET_NAME}"
          hosts:
            - &host "nextcloud.${PUBLIC_DOMAIN}"
    phpClientHttpsFix:
      enabled: true
    nextcloud:
      host: *host
      password: "${NEXTCLOUD_ADMIN_PASSWORD}"
      phpConfigs:
          www.conf: |-
            [www]
            user = www-data
            group = www-data
            listen = 127.0.0.1:9000

            pm = dynamic
            pm.max_children = 20
            pm.start_servers = 5
            pm.min_spare_servers = 5
            pm.max_spare_servers = 15
      configs:
        proxy.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_proxies' => array(
              0 => '127.0.0.1',
              1 => '10.0.0.0/8',
            ),
            'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
          );
        logging.config.php: |-
          <?php
          $CONFIG = array (
            'log_type' => 'file',
            'logfile' => 'nextcloud.log',
            'loglevel' => 1,
          );
        misc.config.php: |-
          <?php
          $CONFIG = array (
            'skeletondirectory' => '',
            'maintenance' => false,
          );
      extraVolumes:
        - name: nfs
          nfs:
            server: "${NFS_SERVER}"
            path: "/media/"
            readOnly: false
      extraVolumeMounts:
        - name: nfs
          mountPath: "/nextcloud-nfs"
    nginx:
      enabled: true
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: mysql
      host: "${MARIADB_SERVICE}"
      user: nextcloud
      password: "${NEXTCLOUD_DATABASE_PASSWORD}"
    persistence:
      enabled: true
      storageClass: "longhorn"
    startupProbe:
      enabled: true
      periodSeconds: 30
      failureThreshold: 10
    livenessProbe:
      enabled: true
      initialDelaySeconds: 60
      periodSeconds: 30
      failureThreshold: 10
    redis:
      enabled: true
      auth:
        enabled: true
        password: "${REDIS_AUTH}"
      master:
        persistence:
          size: 1Gi
          storageClass: "longhorn"
      replica:
        persistence:
          size: 1Gi
          storageClass: "longhorn"
      volumePermissions:
        enabled: true