apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: photoprism
  namespace: photoprism
spec:
  chart:
    spec:
      version: "1.3.2"
  values:
    image:
      repository: photoprism/photoprism
      tag: 221118-arm64
    env:
      TZ: "${TIMEZONE}"
      PHOTOPRISM_STORAGE_PATH: /photoprism/storage
      PHOTOPRISM_ORIGINALS_PATH: /photoprism/originals
      PHOTOPRISM_PUBLIC: "false"
      PHOTOPRISM_DATABASE_DRIVER: mysql
      PHOTOPRISM_DATABASE_SERVER: "${PHOTOPRISM_DATABASE_SERVER}"
      PHOTOPRISM_DATABASE_NAME: photoprism
      PHOTOPRISM_ADMIN_PASSWORD: "${PHOTOPRISM_ADMIN_PASSWORD}"
      PHOTOPRISM_DATABASE_USER: photoprism
      PHOTOPRISM_DATABASE_PASSWORD: "${PHOTOPRISM_DATABASE_PASSWORD}"
      PHOTOPRISM_SITE_AUTHOR: "${PHOTOPRISM_SITE_AUTHOR}"
      PHOTOPRISM_SITE_CAPTION: "Photos by ${PHOTOPRISM_SITE_AUTHOR}"
      PHOTOPRISM_SITE_DESCRIPTION: "Photos by ${PHOTOPRISM_SITE_AUTHOR}"
      PHOTOPRISM_SITE_TITLE: "PhotoPrism"
      PHOTOPRISM_SITE_URL: "https://photos.${PUBLIC_DOMAIN}/"
    service:
      main:
        ports:
          http:
            port: 2342      
    persistence:
      config:
        enabled: true
        mountPath: /photoprism/storage
        storageClass: longhorn
        size: 20Gi
      originals:
        enabled: true
        type: nfs
        server: "${NFS_SERVER}"
        path: /mnt/ext-hdd/media/Photos/
        accessMode: ReadWriteOnce
    ingress:
      main:
        enabled: true
        annotations: 
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/rewrite-target: /$1 
        hosts:
          - 
            host: &host "photos.${PUBLIC_DOMAIN}"
            paths:
              -
                path: /(.*)
                pathType: Prefix
                service:            
                  name: photoprism
                  port: 2342
        tls: 
          - secretName: "${CERT_SECRET_NAME}"
            hosts:
            - *host
      
