---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-immich-pv
spec:
  capacity:
    storage: 400Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: "${NFS_SERVER}"
    path: "/media/Photos/immich"
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-immich-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  volumeName: nfs-immich-pv