apiVersion: v1
kind: PersistentVolume
metadata:
  name: rclone-zurg
  labels:
    name: rclone-zurg
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  storageClassName: rclone
  csi:
    driver: csi-rclone
    volumeHandle: rclone-zurg-data-id
    volumeAttributes:
      remote: "zurg"
      remotePath: ""
      configData: |
        [zurg]
        type = webdav
        url = http://${INGRESS_LB_IP}:9999/dav
        vendor = other
        pacer_min_sleep = 0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rclone-zurg
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  storageClassName: rclone
  selector:
    matchLabels:
      name: rclone-zurg