# Loki
apiVersion: v1
kind: Service
metadata:
  name: loki-proxy
  namespace: wireguard
spec:
  selector:
    app.kubernetes.io/name: wireguard
  type: NodePort
  ports:
    - port: 3100
      targetPort: 3100

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loki
  namespace: wireguard
spec:
  ingressClassName: nginx
  rules:
    - host: loki.internal.${PUBLIC_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: loki-proxy
                port:
                  number: 3100
  tls:
      - secretName: ${CERT_SECRET_NAME}
        hosts:
          - loki.internal.${PUBLIC_DOMAIN}

# Prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-proxy
  namespace: wireguard
spec:
  selector:
    app.kubernetes.io/name: wireguard
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus
  namespace: wireguard
spec:
  ingressClassName: nginx
  rules:
    - host: prom.internal.${PUBLIC_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-proxy
                port:
                  number: 9090
  tls:
      - secretName: ${CERT_SECRET_NAME}
        hosts:
          - prom.internal.${PUBLIC_DOMAIN}