# Loki
apiVersion: v1
kind: Service
metadata:
  name: loki-proxy
  namespace: wireguard
spec:
  selector:
    app.kubernetes.io/name: wireguard
  type: ClusterIP
  ports:
    - port: 3100
      targetPort: 3100

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: loki
  namespace: wireguard
spec:
  parentRefs:
    - name: c0depool-gateway
      namespace: gateways
      sectionName: https
  hostnames:
    - loki.internal.${PUBLIC_DOMAIN}
  rules:
    - backendRefs:
      - name: loki-proxy
        port: 3100
      matches:
      - path:
          type: PathPrefix
          value: /

# Prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-proxy
  namespace: wireguard
spec:
  selector:
    app.kubernetes.io/name: wireguard
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prometheus
  namespace: wireguard
spec:
  parentRefs:
    - name: c0depool-gateway
      namespace: gateways
      sectionName: https
  hostnames:
    - prom.internal.${PUBLIC_DOMAIN}
  rules:
    - backendRefs:
      - name: prometheus-proxy
        port: 9090
      matches:
      - path:
          type: PathPrefix
          value: /