apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jellyseerr
  namespace: jellyseerr
spec:
  releaseName: jellyseerr
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
