apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zurg
  namespace: zurg
spec:
  releaseName: zurg
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
