apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: filebrowser
  namespace: filebrowser
spec:
  releaseName: filebrowser
  chart:
    spec:
      chart: filebrowser
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
