apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: babybuddy
  namespace: babybuddy
spec:
  releaseName: babybuddy
  chart:
    spec:
      chart: babybuddy
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
