apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
  namespace: databases
spec:
  # renovate: datasource=docker depName=ghcr.io/tensorchord/cloudnative-vectorchord
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.3.0
  instances: 1
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
  enableSuperuserAccess: true
  superuserSecret: 
    name: immich-postgres-superuser
  managed:
    roles:
      - name: immich
        superuser: true
        login: true
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-postgres-user
  storage:
    size: 10Gi
    storageClass: longhorn

---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich
spec:
  name: immich
  owner: immich
  cluster:
    name: immich-postgres
  extensions:
    - name: vector
      ensure: present
    - name: vchord
      ensure: present
      version: 0.3.0
    - name: earthdistance
      ensure: present
    - name: vectors
      ensure: absent