apiVersion: v1
kind: Secret
metadata:
  name: immich-postgres-user
  namespace: databases
type: kubernetes.io/basic-auth
stringData:
  username: immich
  password: ${IMMICH_DATABASE_PASSWORD}
---
apiVersion: v1
kind: Secret
metadata:
  name: immich-postgres-superuser
  namespace: databases
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: ${POSTGRES_PASSWORD}