apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  releaseName: immich
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
