apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      version: "4.9.1"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    controller:
      allowSnippetAnnotations: "true"
      config:
        use-forwarded-headers: "true"
        enable-real-ip: "true"
        proxy-real-ip-cidr: 10.0.0.0/8
        custom-http-errors: >-
          401,403,404,500,501,502,503
        # log-format-upstream: >-
        #   $remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_length $request_time [$proxy_upstream_name] [$proxy_alternative_upstream_name] $upstream_addr $upstream_response_length $upstream_response_time $upstream_status $req_id $http_x_forwarded_for
      externalTrafficPolicy: "Local"
      kind: DaemonSet
    defaultBackend:
      enabled: true
      image:
        repository: ghcr.io/tarampampam/error-pages
        tag: 2.26.0
      extraEnvs:
      - name: TEMPLATE_NAME
        value: ghost
      - name: SHOW_DETAILS
        value: "false"
    tcp: 
      "9999": "zurg/zurg:9999"