apiVersion: v1
data:
    plex-secrets.yaml: ENC[AES256_GCM,data:Zf3iwoIKDs9osD06Yf0APefxuK9EAhz0ejCp8kRCORAzqDqLKAN4E1fjkyXJrreL5AVJJUb3jawZgWcVFWVgvMC7Id/1ce0eTpUzIR5Sq9HI2n+yK6wNfotxqoiNmiQVOEmjKLutt4V0NwXvS7H+dF6Gi0K9OURThtK4GYI0jZJzJ0D6T22KYFUx4698UtYP3yyTscGcZwEWfnFne3CrfjtLf2bc2iJAhr6XTP+s5Arccwg737555E9fg0aiO3bRbcsgVeW/9uZtARLu5vbMqAvknFZpwZMbzD2OmzXt6ezPuxgfB9EV6l7o/SzqhzYu3WvD23fcgG5fm2Knrh5jYZksxV6R6qfN+juMAsElrhTW/evaKyFrKC/sc/X/XAHJQbsaEyIVQCgSnBFyX2HqXDijV9XN5ckt0TkdWK/w5tjGAydSskGPGn7IcciY0eZJsnPq6bEfCVPsFra1tF5yI/6b5z2Z0SoEt2V6JduYV/y05TcQXqLgIzofBHSFudppVlc5em+5kGnxRnkiW42YBeoIkfUtpWKLLHwY7sWnPgINB0WIMMHAaWavnsdJDtDA3IqfuV35XguyjLblW/NI8bJJr8e7HCrynyoZ0NDqe7BoUHChR3HirW6TW2vj/vyGkjL02hnLQOhU/3grX4rGcafVkw8ugv90kOXUiQsAxHm16Bq+DPWG+Z84qsyz2Pm0qrPusdcmwYVkjVBdFviKs+niiQqrOVnDszH6lkUcIctXxVPuCqCMMFtSoRHEET+STTZCR+sHybJPN7T2GZzxjR3nWS1scg1QLsSAgBtk234/4x9LB934FMccggnA6wfbYCTeepMNf7RP7z3vIc1Yg9gOcnjyoVfDhDTndnp/O+IesF3E22Ws2I0Xta8pa2XOpzxSEe4OQxrPyQFwr6tYy2V8Zep2Wmu61pP9x2woAzlbdmYENDrlg5f2ylEEbHFh0mB9S0ArgD9cev+a3sgbcy9Vh1LVpINhCksUl2rEdUDVIQDgzjuSL/zeNL9TOWx8xc/0ST3ifABItP776OWShagugvcLu8A8/eeJQQXITZ34jssBNZ1WGMScl2fopJUU3TPoaNh1361IJT6ooE/aMwWQSPOf8senQbLvlGtEM164n7tDpA+mQHIbEQe5gDsx,iv:0uXkqUhqQYDcIYt2uec4Dejj841ERM5HQg1K0WPhSTA=,tag:OoX74SugDqWxh04Lpn5bfg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: plex-secrets
    namespace: plex
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1697e27xddkfkesylswayhk6ms8pln48e6nem2lrwe97yg8tenyysppqw9t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbk5XR1BaT2dnRS9yWGNL
            enJNS3Z0eU5wTWthblFKZHpzcE00R1dGRlQ4CnhlTkllQkJrbzgwYWRibG9HNTlV
            QkNjZ1hOSW5yTGE1WGFTa0wzNW8zVG8KLS0tIFY2cFNEUGs3THkxcGZoOHFueTEz
            WjVkOGIzUktwY0hiMnoyak1RanMzMUUKTAsxwZGbDePCApLhEKW7JzOXDRNMwJ+Y
            sCYWAbhimWv/8ScObl7U/ozzEaUI4J1mm/Dgd0M6bc6B66LqQfWqjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-08T14:15:23Z"
    mac: ENC[AES256_GCM,data:pFM73mWjkq3sBNPw/p7z81Pay1Y/qIisXQwZ96g4GoVo3tbVeW6ExoCKOnwS7IxIF+3+/cEQo0ndsqctumedbj3xRvwAW1eM4lAMkZw8p5DEW+NfByMWJdh5n5UTB+Tyyplgc+PWYSoXFgn6bHKnQWGLw/ghDKu6+AfxZpbLTs0=,iv:fT6gFjGkQQEvvZAW9Q+GGxfn9Gnc3kct42QXBuIgSxs=,tag:DlOwp5OHHrUs12jb3oZJyg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
